---

  - include_tasks: fpm.centos.yml
    when: ansible_distribution == "CentOS"

  - include_tasks: fpm.centos.yml
    when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

  - import_tasks: fpm.debian.yml
    when: ansible_distribution == "Debian"

...