---
    - name: Instalando Zabbix Agent para Amazon 2
      yum:
        name: "{{ url_agent_amazonna2}}"
        state: present
      when: ansible_distribution_version == "(Karoo)"

    - name: Instalando Zabbix Agent para Amazon
      yum:
        name: "{{ url_agent_amazonna }}"
        state: present
      when: ansible_distribution_version != "(Karoo)"

    - name: Instalando python-pip
      yum:
        name: python-pip

    - name: Instalando modulos boto
      pip:
        name: boto3, botocore

    - name: Pegando InstanceID
      uri:
        url: http://169.254.169.254/latest/meta-data/instance-id
        return_content: yes
      register: id

    - name: Registrando TAG Name da instancia
      ec2_tag:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region:  us-east-1
        resource: '{{ id.content }}'
        state: list
        tags:
          Name: Name
      register: zabbix_hostname

    - debug:
        msg: '{{ zabbix_hostname | json_query("tags.Name") }}'

    - name: Aplicando config do Zabbix
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - Restart Zabbix Agent

    - name: Iniciar Zabbix com sistema
      service:
        name: zabbix-agent
        enabled: yes