---
  - name: restart zabbix-server
    service:
      name: zabbix-server
      state: restarted

  - name: restart mysql
    service:
      name: mysqld
      state: started
      enabled: yes

  - name: Start zabbix-server
    service:
      name: zabbix-server
      state: started
      enabled: yes

  - name: Start zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: yes

  - name: restart zabbix-agent
    service:
      name: zabbix-agent
      state: restarted