---

  - name: Install MySQL repository (Centos 7)
    yum_repository:
      name: RepoMYSQL
      description: MYSQL Packages for Enterprise Linux 7
      baseurl: http://repo.mysql.com/yum/{{mysql_release_redhat}}/el/7/{{ ansible_architecture }}/
      gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
      gpgcheck: yes
    tags: mysql

  - name: Install MySQL packages
    package:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - "{{ mysql_packages[ansible_distribution] }}"
    notify:
      - restart mysql docker
      - restart mysql
    tags: mysql

  - name: Copy MYSQL template configuration to host
    template:
      src: etc/mysql/my.cnf.j2
      dest: /etc/my.cnf
    notify:
      - restart mysql docker
      - restart mysql
    tags: mysql
...